apiVersion: v1
kind: Pod
metadata:
  name: fleetman-webapp
  labels:
    app: fleetman
    component: webapp
    version: release1
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    # Resource limits and requests
    resources:
      limits:
        memory: "256Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "100m"
#    # Environment variables for webapp configuration
#    env:
#    - name: SPRING_PROFILES_ACTIVE
#      value: "production"
#    # Liveness probe
#    livenessProbe:
#      httpGet:
#        path: /
#        port: 80
#      initialDelaySeconds: 30
#      periodSeconds: 10
#      timeoutSeconds: 5
#      failureThreshold: 3
#    # Readiness probe
#    readinessProbe:
#      httpGet:
#        path: /
#        port: 80
#      initialDelaySeconds: 10
#      periodSeconds: 5
#      timeoutSeconds: 3
#      successThreshold: 1
#      failureThreshold: 3
#  # Restart policy
#  restartPolicy: Always
