apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  restartPolicy: Always
  containers:
    - name: nginx
      image: nginx:1.21.6   # 使用 Nginx 官方镜像
      imagePullPolicy: Always
      ports:
        - containerPort: 80   # 暴露 Nginx 服务器的 80 端口



---

