apiVersion: v1
kind: Pod
metadata:
  name: prob-pod
  labels:
    app: nginx
spec:
  terminationGracePeriodSeconds: 30
  restartPolicy: Always
  containers:
    - name: nginx
      image: nginx:1.27.2-alpine
      imagePullPolicy: Always
      ports:
        - containerPort: 80
      startupProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
        failureThreshold: 5
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 20
        periodSeconds: 10
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3



---

