apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
spec:
  containers:
    - name: web-app
      image: nginx:1.27.2-alpine  # 主容器运行 Web 应用的镜像
      ports:
        - containerPort: 80
      env:
        - name: DB_HOST
          value: mysql-service  # 数据库的服务名
        - name: DB_PORT
          value: "3306"

  initContainers:
    - name: init-db-check
      image: busybox
      command:
        - sh
        - "-c"
        - >
          until nc -z $DB_HOST $DB_PORT;
          do
            echo "Waiting for database connection...";
            sleep 10;
          done;
          echo "Database is up!";
      env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_PORT
          value: "3306"
