apiVersion: v1
kind: Pod
metadata:
  name: test-busybox
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"  # 保持容器运行1小时
    resources:
      limits:
        memory: "64Mi"
        cpu: "100m"
