apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx
    tier: frontend
spec:
  # 定义需要维护的副本数
  replicas: 3
  # 选择器，用于确定哪些 Pod 属于这个 ReplicaSet
  selector:
    matchLabels:
      app: nginx
      version: "2"  # 添加 version 标签到 selector
  # Pod 模板
  template:
    metadata:
      labels:
        app: nginx
        version: "2"  # 确保与 selector 匹配
    spec:
      containers:
      - name: nginx
        image: nginx:1.26.3-alpine3.20-perl
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        command:
        - sh
        - -c
        - |
          nginx -v &> /tmp/version;
          echo "Nginx Version: $(cat /tmp/version)";
          while true; do 
            echo "Running Nginx Version: $(cat /tmp/version)"; 
            sleep 10; 
          done