apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  # Service will route traffic to Pods with labels matching the selector
  selector:
    app: webapp
  ports:
  - name: http
    port: 80        # Service port
    targetPort: 80  # Container port
    nodePort: 30080 # NodePort for external access (30000-32767)
  type: NodePort    # Expose service on each Node's IP at a static port
