apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
    type: frontend
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0
    ports:
    - containerPort: 80
      name: http
