apiVersion: v1
kind: Pod
metadata:
  name: webapp0
  labels:
    app: webapp
    type: frontend
    version: "0"  # Labels must be strings
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0
    ports:
    - containerPort: 80
      name: http

---

apiVersion: v1
kind: Pod
metadata:
  name: webapp0-5
  labels:
    app: webapp
    type: frontend
    version: "0-5"  # Labels must be strings
spec:
  containers:
    - name: webapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
      ports:
        - containerPort: 80
          name: http

