# webapp
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-webapp
  labels:
    app: fleetman-webapp
    version: "1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fleetman-webapp
  template:
    metadata:
      labels:
        app: fleetman-webapp
    spec:
      containers:
      - name: fleetman-webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release1
        ports:
        - containerPort: 80
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: production-microservice

---
# queue
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-queue
  template:
    metadata:
      labels:
        app: fleetman-queue
    spec:
      containers:
        - name: fleetman-queue
          image: richardchesterwood/k8s-fleetman-queue:release1

---
# position simulator
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-position-simulator
  template:
    metadata:
      labels:
        app: fleetman-position-simulator
    spec:
      containers:
        - name: fleetman-position-simulator
          image: richardchesterwood/k8s-fleetman-position-simulator:release1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice

---
# position tracker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-position-tracker
  template:
    metadata:
      labels:
        app: fleetman-position-tracker
    spec:
      containers:
        - name: fleetman-position-tracker
          image: richardchesterwood/k8s-fleetman-position-tracker:release1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice

---
# position tracker
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-api-gateway
  template:
    metadata:
      labels:
        app: fleetman-api-gateway
    spec:
      containers:
        - name: fleetman-api-gateway
          image: richardchesterwood/k8s-fleetman-api-gateway:release1
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice