apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-webapp-basic
  labels:
    app: fleetman-webapp
    version: basic
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fleetman-webapp
      version: basic
  template:
    metadata:
      labels:
        app: fleetman-webapp
        version: basic
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp-service
spec:
  selector:
    app: fleetman-webapp
    version: basic
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
